name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Run Android tests
      run: ./gradlew test

    - name: Run Android tests
      run: ./gradlew connectedAndroidTest

    - name: Prepare demo files
      run: |
        mdkir build_gh_pages
        cd build_gh_pages
        adb pull '/sdcard/clickAndWaitForWhile.mp4'
        
